"""Carolina Faccin's visual identity for matplotlib figures: colors, data palettes,
Source Code Pro and the figure layout (header, footer, scale bar).

Vendored from the private repository lina-brand. Do not edit this copy: edit
lina-brand (tokens/tokens.json, palettes/palettes.json or python/brand.py) and run
`npm run sync` there.

Each repository keeps a thin style.py that sets its source line and repository name:

    from .brand import *            # colors, palettes and helpers
    from . import brand
    SOURCE = "Source: ..."
    REPO = "github.com/carolinafaccin/<repo>"
    def setup(): brand.setup(ROOT / "assets" / "fonts")
    def footer(fig, note=SOURCE): brand.footer(fig, note, REPO)
"""
# matplotlib is imported inside the functions, so scripts that only need the colors
# (e.g. the site's cover renderer, which uses Pillow) do not depend on it.

# >>> generated by scripts/build.mjs from tokens.json and palettes.json
# GERADO por lina-brand/scripts/build.mjs — não edite à mão; edite tokens/tokens.json ou palettes/palettes.json.
# Designer palette
CREAM = "#FFF8F3"
PEACH = "#FFD5C2"
YELLOW = "#FFD348"
ORANGE = "#D94701"
RUST = "#7E2704"
SAGE = "#92A87E"
SAGE_LIGHT = "#CCD5C2"
OLIVE = "#383D2F"
DARK = "#1F2417"
# Support colors
GREY = "#DAD2CC"
MUTED = "#737464"
GRID = "#E7E1DA"
LAND = "#F4F0EA"
SAGE_DARK = "#5C704C"
ORANGE_LIGHT = "#F5A078"
# Data palettes (validated with the dataviz palette validator, white surface)
CATEGORIAS = ["#5E8A3F", "#8C2F0C", "#D94701", "#D4A72C"]
OUTROS = ["#9A958F"]
LARANJA = ["#F0A07A", "#E2733D", "#C24A12", "#8E300B", "#561A03"]
VERDE = ["#A3BC88", "#6E9A4D", "#40682A", "#26451A"]
OCRE = ["#CDAA3E", "#A88412", "#7A600D", "#4D3C07"]
# Map colors
MAP_LAND = "#F4F0EA"
MAP_WATER = "#CCD5C2"
MAP_FLOOD = "#FFD5C2"
MAP_LINE = "#383D2F"
MAP_CONTEXT = "#DAD2CC"
# <<< generated

# Figure aliases
INK = OLIVE           # text and outlines in figures (the site text color is DARK)
WATER = SAGE_LIGHT
SAGE_L = SAGE_LIGHT
SAGE_D = SAGE_DARK
CAT = CATEGORIAS      # categorical, fixed order, never cycled
OTHER = OUTROS[0]     # "other / mixed" category
SEQ = LARANJA         # main ordinal ramp
SEQ_GREEN = VERDE
SEQ_OCHRE = OCRE


def setup(fonts_dir=None):
    """Register Source Code Pro (the .ttf files in fonts_dir) and set the matplotlib defaults."""
    import matplotlib as mpl
    from matplotlib import font_manager as fm

    if fonts_dir is not None:
        for f in sorted(fonts_dir.glob("*.ttf")):
            fm.fontManager.addfont(str(f))
    families = {f.name for f in fm.fontManager.ttflist}
    mpl.rcParams.update({
        "font.family": "Source Code Pro" if "Source Code Pro" in families else "monospace",
        "font.size": 9.5,
        "text.color": INK,
        "axes.edgecolor": GREY,
        "axes.labelcolor": MUTED,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "axes.grid": True,
        "axes.axisbelow": True,
        "grid.color": GRID,
        "grid.linewidth": 0.8,
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "legend.frameon": False,
        "savefig.facecolor": "white",
    })


def header(fig, title, subtitle=None):
    """Title and subtitle at a fixed distance (in inches) from the top edge."""
    h = fig.get_figheight()
    fig.text(0.04, 1 - 0.35 / h, title, fontsize=15, fontweight="semibold", ha="left", va="top", color=INK)
    if subtitle:
        fig.text(0.04, 1 - 0.78 / h, subtitle, fontsize=9.5, ha="left", va="top", color=MUTED, linespacing=1.5)


def footer(fig, note, repo):
    """Source and repository, two lines at a fixed distance (in inches) from the bottom."""
    h = fig.get_figheight()
    fig.text(0.04, 0.22 / h, note, fontsize=7.5, ha="left", va="bottom", color=MUTED)
    fig.text(0.04, 0.06 / h, repo, fontsize=7.5, ha="left", va="bottom", color=MUTED)


def frac(fig, inches):
    """Inches from the top edge as a figure fraction (for subplots_adjust top=...)."""
    return 1 - inches / fig.get_figheight()


def bottom(fig, inches):
    return inches / fig.get_figheight()


def text_on(fill):
    """White or ink, whichever reads better on a filled mark."""
    import matplotlib as mpl

    r, g, b = mpl.colors.to_rgb(fill)
    lum = 0.2126 * r ** 2.2 + 0.7152 * g ** 2.2 + 0.0722 * b ** 2.2
    return "white" if lum < 0.3 else INK


def halo(width=2.5):
    import matplotlib.patheffects as pe

    return [pe.withStroke(linewidth=width, foreground="white")]


def scalebar(ax, km=2, loc=(0.05, 0.05)):
    """Scale bar in projected metres, placed in axes fraction."""
    x0, x1 = ax.get_xlim()
    y0, y1 = ax.get_ylim()
    x, y = x0 + (x1 - x0) * loc[0], y0 + (y1 - y0) * loc[1]
    ax.plot([x, x + km * 1000], [y, y], color=INK, lw=2, solid_capstyle="butt")
    ax.text(x + km * 500, y + (y1 - y0) * 0.012, f"{km:g} km", ha="center", va="bottom", fontsize=8, color=INK)


def map_axes(ax, bounds, pad=600):
    minx, miny, maxx, maxy = bounds
    ax.set_xlim(minx - pad, maxx + pad)
    ax.set_ylim(miny - pad, maxy + pad)
    ax.set_aspect("equal")
    ax.axis("off")


def save(fig, path, dpi=200):
    import matplotlib.pyplot as plt

    fig.savefig(path, dpi=dpi)
    plt.close(fig)
